apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-binding
subjects:
  - kind: Group
    name: administrators
    namespace: ""  # Required for Group, leave empty
roleRef:
  kind: ClusterRole
  name: admin  # Replace with the desired ClusterRole
  apiGroup: rbac.authorization.k8s.io