apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: discovery-binding
subjects:
- kind: User
  name: discovery # Use as the Identity Alias Healthcheck Username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: discovery
  apiGroup: rbac.authorization.k8s.io