apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: engineering-binding
subjects:
  - kind: Group
    name: engineering
    namespace: ""  # Required for Group, leave empty
roleRef:
  kind: ClusterRole
  name: edit  # Replace with the desired ClusterRole
  apiGroup: rbac.authorization.k8s.io