apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdm-health-binding
subjects:
- kind: User
  name: sdm-health # Use as the Identity Alias Healthcheck Username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sdm-health
  apiGroup: rbac.authorization.k8s.io