apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-binding
subjects:
  - kind: Group
    name: read-only
    namespace: ""  # Required for Group, leave empty
roleRef:
  kind: ClusterRole
  name: read  # Replace with the desired ClusterRole
  apiGroup: rbac.authorization.k8s.io