apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readonly-binding
subjects:
  - kind: Group
    name: readonly
    namespace: "" # Required for Group, leave empty
roleRef:
  kind: ClusterRole
  name: view # Replace with the desired ClusterRole
  apiGroup: rbac.authorization.k8s.io
